/*
 * DataStructuresAssignmentView.java
 */

package datastructuresassignment;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Time;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The application's main frame.
 */
public class DataStructuresAssignmentView extends FrameView {
String str_TextToSearch = 
                "Hello World!, Hello Universe!\n"
                +"Hello World!, Hello Universe!\n"
                +"Hello World!, Hello Universe!\n"
                +"Hello World!, Hello Universe!\n"
                +"Hello World!, Hello Universe!\n"
                +"Hello World!, Hello Universe!\n"
                +"Hello World!, Hello Universe!\n"
                +"Hello World!, Hello Universe!\n"
                +"Hello World!, Hello Universe!\n"
                +"Hello World!, Hello Universe!\n"
                +"Hello World!, Hello Universe!\n";
     
    public DataStructuresAssignmentView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                }
            }
        });
        this.jTextArea_SearchResults.setText(str_TextToSearch);
        this.jTextField_SearchText.setText("ello");
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = DataStructuresAssignmentApp.getApplication().getMainFrame();
            aboutBox = new DataStructuresAssignmentAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        DataStructuresAssignmentApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_SearchResults = new javax.swing.JTextArea();
        jTextField_SearchText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_ResultsArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();

        mainPanel.setName("mainPanel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(datastructuresassignment.DataStructuresAssignmentApp.class).getContext().getActionMap(DataStructuresAssignmentView.class, this);
        jButton1.setAction(actionMap.get("quit")); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(datastructuresassignment.DataStructuresAssignmentApp.class).getContext().getResourceMap(DataStructuresAssignmentView.class);
        jButton1.setText(resourceMap.getString("jButton_Exit.text")); // NOI18N
        jButton1.setName("jButton_Exit"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea_SearchResults.setColumns(20);
        jTextArea_SearchResults.setFont(resourceMap.getFont("jTextArea_SearchResults.font")); // NOI18N
        jTextArea_SearchResults.setLineWrap(true);
        jTextArea_SearchResults.setRows(5);
        jTextArea_SearchResults.setName("jTextArea_SearchResults"); // NOI18N
        jScrollPane1.setViewportView(jTextArea_SearchResults);

        jTextField_SearchText.setText(resourceMap.getString("jTextField_SearchText.text")); // NOI18N
        jTextField_SearchText.setName("jTextField_SearchText"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel_SearchText.text")); // NOI18N
        jLabel1.setToolTipText(resourceMap.getString("jLabel_SearchText.toolTipText")); // NOI18N
        jLabel1.setName("jLabel_SearchText"); // NOI18N

        jButton2.setAction(actionMap.get("DerekKeoghSearch")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton_DerekKeoghSearch.text")); // NOI18N
        jButton2.setName("jButton_DerekKeoghSearch"); // NOI18N

        jButton3.setAction(actionMap.get("RabinKarpSearch")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton_RabinKarpSearch.text")); // NOI18N
        jButton3.setToolTipText(resourceMap.getString("jButton_RabinKarpSearch.toolTipText")); // NOI18N
        jButton3.setName("jButton_RabinKarpSearch"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTextArea_ResultsArea.setColumns(20);
        jTextArea_ResultsArea.setLineWrap(true);
        jTextArea_ResultsArea.setRows(5);
        jTextArea_ResultsArea.setName("jTextArea_ResultsArea"); // NOI18N
        jScrollPane2.setViewportView(jTextArea_ResultsArea);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(658, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jTextField_SearchText, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(697, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_SearchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setComponent(mainPanel);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void DerekKeoghSearch() {

        str_TextToSearch = this.jTextArea_SearchResults.getText();
        
        String str_SearchFor = this.jTextField_SearchText.getText();
        
        DKStringFinder obj_DKStringFinder = new DKStringFinder();
        
        //this.jTextArea_ResultsArea.append("\n\nBrute Force Search for First\n");
        //this.jTextArea_ResultsArea.append(obj_DKStringFinder.str_BruteForceSearchForFirstMatch(str_TextToSearch, str_SearchFor));

        //this.jTextArea_ResultsArea.append("\nBrute Force Search for All\n\n");
        //this.jTextArea_ResultsArea.append(obj_DKStringFinder.str_BruteForceSearchForAll(str_TextToSearch, str_SearchFor));
        
        if(true){
        
        int i_SearchReturnValue = obj_DKStringFinder.i_StringSearch(str_TextToSearch, str_SearchFor);
        
        this.jTextArea_ResultsArea.append("\n-----------Start Derek Keogh Search-----------------------\n");
        if (i_SearchReturnValue > 0)
        {
            this.jTextArea_ResultsArea.append("\nfound " + i_SearchReturnValue + " copies of " + str_SearchFor + "\n");
            this.jTextArea_ResultsArea.append("\nfound at location: " + obj_DKStringFinder.get_strGetMatchLocations() + "\n");
        }else if (i_SearchReturnValue == 0)
        {
            this.jTextArea_ResultsArea.append("\nSearch string " + str_SearchFor + " not found");
        }else if (i_SearchReturnValue <= -1)
        {
            this.jTextArea_ResultsArea.append("\nProblem with your search string: " + str_SearchFor);
        }
        this.jTextArea_ResultsArea.append("\n-----------End Derek Keogh Search-----------------------\n");
        }
    }

    @Action
    public void Exit() {
    }

    @Action
    public void RabinKarpSearch() {
        
        str_TextToSearch = this.jTextArea_SearchResults.getText();
        String str_SearchFor = this.jTextField_SearchText.getText();
    
        RabinKarp searcher = new RabinKarp(str_SearchFor);
        String  str_offset = searcher.search(str_TextToSearch);

        this.jTextArea_ResultsArea.append("\n-----------Start Rabin Karp Search-----------------------\n");
       
        if(searcher.get_iMatchCount() > 0){
            // from brute force search method 1
            this.jTextArea_ResultsArea.append("\nfound " + searcher.get_iMatchCount() + " copies of " + str_SearchFor + "\n");
            this.jTextArea_ResultsArea.append("\nfound at location: " + str_offset +"\n");
        }else
        {
            this.jTextArea_ResultsArea.append("\nSearch string " + str_SearchFor + " not found\n");
        }

        this.jTextArea_ResultsArea.append("\n-----------End Rabin Karp Search-----------------------\n");
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea_ResultsArea;
    private javax.swing.JTextArea jTextArea_SearchResults;
    private javax.swing.JTextField jTextField_SearchText;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
